# Generated by Django 5.2.5 on 2025-10-23 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='الرقم التعريفي')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('grade', models.CharField(max_length=20, verbose_name='الفصل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='طالب نشط')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quran')),
                ('islamic', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Islamic')),
                ('arabic', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Arabic')),
                ('math', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Math')),
                ('physics', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Physics')),
                ('chemistry', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chemistry')),
                ('biology', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Biology')),
                ('english', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='English')),
                ('behavior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Behavior')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
        ),
    ]
