# Generated by Django 5.2.5 on 2025-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='arabic',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عربي'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='behavior',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='سلوك'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='biology',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='احياء'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='chemistry',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='كيمياء'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='english',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='انحليزي'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='islamic',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='اسلامية'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='math',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='رياضيات'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='physics',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='فيزياء'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='quran',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='قرءان'),
        ),
    ]
