# Generated by Django 5.2.5 on 2025-10-30 11:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'صفوف دراسية',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='الشهر')),
                ('order', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهور',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)], verbose_name='الرقم التعريفي')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)], verbose_name='الرقم التعريفي')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='الاسم')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'طلاب',
                'ordering': ['classroom', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'منسحب')], default='active', max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='المادة')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_by_classroom', to='core.classroom', verbose_name='الصف')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_by_teacher', to='core.teacher', verbose_name='المدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='السنة')),
                ('value', models.FloatField(help_text='أدخل الدرجة من 0 إلى 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_by_month', to='core.month')),
                ('grade_fo_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_by_student', to='core.student', verbose_name='الطالب')),
                ('grade_fo_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_by_subject', to='core.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'درجات',
                'ordering': ['year', 'month', 'value'],
                'unique_together': {('grade_fo_student', 'grade_fo_subject', 'month', 'year')},
            },
        ),
    ]
