# Generated by Django 5.2.8 on 2025-11-10 14:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='اسم الصف')),
                ('order', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='المستوى الدراسي')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'صفوف دراسية',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='الشهر')),
                ('order', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهور',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)], verbose_name='الرقم التعريفي')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('specialty', models.CharField(blank=True, max_length=50, verbose_name='التخصص')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='صورة المدرس')),
                ('bio', models.TextField(blank=True, verbose_name='معلومات إضافية عن المدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(auto_created=True, verbose_name='نشط')),
                ('student_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)], verbose_name='الرقم التعريفي')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريه التسجيل')),
                ('address', models.TextField(max_length=50, verbose_name='العنوان')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='صورة الطالب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'طلاب',
                'ordering': ['classroom', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المادة')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_by_classroom', to='core.classroom', verbose_name='الصف')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_by_teacher', to='core.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'مواد',
                'ordering': ['classroom', 'name'],
                'unique_together': {('name', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='السنة')),
                ('value', models.FloatField(help_text='أدخل الدرجة من 0 إلى 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.month', verbose_name='الشهر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'درجات',
                'ordering': ['year', 'month', 'subject', 'value'],
                'unique_together': {('student', 'subject', 'month', 'year')},
            },
        ),
    ]
