# Generated by Django 5.2.5 on 2025-10-24 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='الرقم التعريفي')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدرس')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(choices=[('quran', 'quran'), ('islamic', 'islamic'), ('arabic', 'arabic'), ('math', 'math'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('english', 'english'), ('Active', 'Active')], max_length=20, verbose_name='المادة')),
            ],
        ),
    ]
