# Generated by Django 5.2.5 on 2025-11-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
